on:
  push:
    branches: [ main ]
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build and publish
        run: |
          cd V8-R8-Hub
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ../v8-r8-hub-build -r linux-x64 --self-contained true /p:UseAppHost=true
      - name: Bundle build
        run: |
          tar -czvf build.tar.gz v8-r8-hub-build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build.tar.gz
