name: Publish release
run-name: Publish release ${{github.ref}}

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build and publish backend
        run: |
          cd V8-R8-Hub
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ../v8-r8-hub-build -r linux-x64 --self-contained true /p:UseAppHost=true
      - name: Build and publish upgrader
        run: |
          cd DbUpgrader
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ../upgrader-build -r linux-x64 --self-contained true /p:UseAppHost=true
      - name: Bundle build
        run: |
          tar -czvf backend-build.tar.gz v8-r8-hub-build
          tar -czvf upgrader-build.tar.gz upgrader-build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            backend-build.tar.gz
            upgrader-build.tar.gz
      
