name: Backend unit tests
run-name: Backend unit test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Bootstrap upgrader
        run: ./.github/test-bootstrap.sh
      - name: Run all upgraders
        run: ./DbUpgrader/bin/Debug/net7.0/DbUpgrader upgrade-latest
      - name: Run all downgraders
        run: ./DbUpgrader/bin/Debug/net7.0/DbUpgrader upgrade InitUpgrader --allow-down
      - name: Run all upgraders
        run: ./DbUpgrader/bin/Debug/net7.0/DbUpgrader upgrade-latest